"""Catálogo inicial (seed) de sinais de risco e do playbook de ações.

Os limiares vêm do planejamento (§6.2). Enquanto não há calibração, todos os
sinais têm o mesmo peso (0,10 — soma 1). `metrica` diz qual indicador a regra
NIVEL compara (média ou soma dos últimos 3 meses).
"""

from app.core.enums import Dimensao, Responsavel, SentidoPiora, TipoRegra

PESO_INICIAL = 0.10

SINAIS_SEED: list[dict] = [
    {
        "codigo": "REABERTOS_TENDENCIA",
        "dimensao": Dimensao.ATENDIMENTO,
        "variavel": "chamados_reabertos",
        "tipo_regra": TipoRegra.TENDENCIA,
        "sentido_piora": SentidoPiora.AUMENTO,
        "limiar": 0.50,
        "metrica": "media_3m",
        "template_evidencia": "Chamados reabertos subiram {variacao_pct:.0%} nos últimos 3 meses em relação à média anterior",
    },
    {
        "codigo": "CRITICOS_TENDENCIA",
        "dimensao": Dimensao.ATENDIMENTO,
        "variavel": "chamados_criticos",
        "tipo_regra": TipoRegra.TENDENCIA,
        "sentido_piora": SentidoPiora.AUMENTO,
        "limiar": 0.50,
        "metrica": "media_3m",
        "template_evidencia": "Chamados críticos subiram {variacao_pct:.0%} nos últimos 3 meses em relação à média anterior",
    },
    {
        "codigo": "RESOLUCAO_LENTA",
        "dimensao": Dimensao.SLA,
        "variavel": "tempo_resolucao_vs_sla",
        "tipo_regra": TipoRegra.TENDENCIA,
        "sentido_piora": SentidoPiora.AUMENTO,
        "limiar": 0.25,
        "metrica": "media_3m",
        "template_evidencia": "Tempo de resolução em relação ao SLA piorou {variacao_pct:.0%} nos últimos 3 meses",
    },
    {
        "codigo": "SLA_BAIXO",
        "dimensao": Dimensao.SLA,
        "variavel": "pct_sla_cumprido",
        "tipo_regra": TipoRegra.NIVEL,
        "sentido_piora": SentidoPiora.QUEDA,
        "limiar": 65,
        "metrica": "media_3m",
        "template_evidencia": "SLA cumprido em {media_3m:.0f}% na média dos últimos 3 meses (limite: 65%)",
    },
    {
        "codigo": "USO_EM_QUEDA",
        "dimensao": Dimensao.ENGAJAMENTO,
        "variavel": "uso_plataforma_pct",
        "tipo_regra": TipoRegra.TENDENCIA,
        "sentido_piora": SentidoPiora.QUEDA,
        "limiar": 0.15,
        "metrica": "media_3m",
        "template_evidencia": "Uso da plataforma caiu {queda_pct:.0%} em relação à média anterior",
    },
    {
        "codigo": "REUNIOES_CANCELADAS",
        "dimensao": Dimensao.ENGAJAMENTO,
        "variavel": "pct_reunioes_realizadas",
        "tipo_regra": TipoRegra.NIVEL,
        "sentido_piora": SentidoPiora.QUEDA,
        "limiar": 0.5,
        "metrica": "media_3m",
        "template_evidencia": "Apenas {media_3m:.0%} das reuniões previstas aconteceram nos últimos 3 meses",
    },
    {
        "codigo": "ATRASO_PAGAMENTO",
        "dimensao": Dimensao.FINANCEIRO,
        "variavel": "dias_atraso_pagamento",
        "tipo_regra": TipoRegra.NIVEL,
        "sentido_piora": SentidoPiora.AUMENTO,
        "limiar": 6,
        "metrica": "media_3m",
        "template_evidencia": "Atraso médio de pagamento de {media_3m:.1f} dias nos últimos 3 meses",
    },
    {
        "codigo": "RECLAMACOES",
        "dimensao": Dimensao.SATISFACAO,
        "variavel": "reclamacoes_formais",
        "tipo_regra": TipoRegra.NIVEL,
        "sentido_piora": SentidoPiora.AUMENTO,
        "limiar": 2,
        "metrica": "soma_3m",
        "template_evidencia": "{soma_3m:.0f} reclamações formais nos últimos 3 meses",
    },
    {
        "codigo": "NPS_EM_QUEDA",
        "dimensao": Dimensao.SATISFACAO,
        "variavel": "nps_variacao",
        "tipo_regra": TipoRegra.EVENTO,
        "sentido_piora": SentidoPiora.QUEDA,
        "limiar": 2,
        "metrica": "media_3m",
        "template_evidencia": "Nota de NPS caiu {queda_abs:.0f} pontos na última pesquisa respondida",
    },
    {
        "codigo": "NPS_SILENCIO",
        "dimensao": Dimensao.SATISFACAO,
        "variavel": "nps_sem_resposta_consecutivas",
        "tipo_regra": TipoRegra.EVENTO,
        "sentido_piora": SentidoPiora.AUMENTO,
        "limiar": 1,
        "metrica": "media_3m",
        "template_evidencia": "Não respondeu às {valor_mes:.0f} últimas pesquisas de NPS",
    },
]

ACOES_SEED: list[dict] = [
    {
        "codigo": "COMITE_RETENCAO",
        "titulo": "Ação coordenada de retenção",
        "descricao": "O risco afeta várias dimensões ao mesmo tempo: montar um comitê com CS, técnico e executivo e definir um plano único para o cliente.",
        "dimensao_gatilho": None,
        "responsavel_sugerido": Responsavel.EXECUTIVO,
        "prazo_dias": 7,
        "ordem": 1,
    },
    {
        "codigo": "CONTATO_EXECUTIVO",
        "titulo": "Contato executivo",
        "descricao": "O cliente sumiu das reuniões e parou de responder ao NPS: um executivo deve procurar o patrocinador do contrato.",
        "dimensao_gatilho": Dimensao.ENGAJAMENTO,
        "responsavel_sugerido": Responsavel.EXECUTIVO,
        "prazo_dias": 7,
        "ordem": 2,
    },
    {
        "codigo": "REVISAO_TECNICA",
        "titulo": "Revisão técnica dos chamados",
        "descricao": "Revisar chamados reabertos, críticos e fora do SLA, escalar internamente e apresentar um plano de correção.",
        "dimensao_gatilho": Dimensao.ATENDIMENTO,
        "responsavel_sugerido": Responsavel.TECNICO,
        "prazo_dias": 15,
        "ordem": 3,
    },
    {
        "codigo": "REUNIAO_VALOR",
        "titulo": "Reunião de valor e reonboarding",
        "descricao": "Agendar uma reunião para mostrar o valor entregue e reengajar o uso da plataforma.",
        "dimensao_gatilho": Dimensao.ENGAJAMENTO,
        "responsavel_sugerido": Responsavel.CS,
        "prazo_dias": 15,
        "ordem": 4,
    },
    {
        "codigo": "CONVERSA_FINANCEIRA",
        "titulo": "Conversa financeira",
        "descricao": "Entender o motivo dos atrasos de pagamento e negociar condições.",
        "dimensao_gatilho": Dimensao.FINANCEIRO,
        "responsavel_sugerido": Responsavel.FINANCEIRO,
        "prazo_dias": 15,
        "ordem": 5,
    },
    {
        "codigo": "PLANO_DE_RECUPERACAO",
        "titulo": "Plano de recuperação da satisfação",
        "descricao": "Tratar as reclamações e a queda de NPS com um plano de ação acompanhado pelo CS.",
        "dimensao_gatilho": Dimensao.SATISFACAO,
        "responsavel_sugerido": Responsavel.CS,
        "prazo_dias": 15,
        "ordem": 6,
    },
]
